### PR TITLE
Warn when encountering unknown attributes instead of bailing out.

### LINKED ISSUE #535: Xcodeproj doesn't know about the following attributes {"refType"=>"0"} for the 'PBXFileReference' isa. (RuntimeError)
I am generating my Qt application with [fastlane](https://fastlane.tools).
`project.pbxproj` which is created by it, obviously doesn't work okay, since it breaks at `Xcodeproj::Project.open`. Further logs below:

```
/Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:321:in `configure_with_plist': [!] [!] Xcodeproj doesn't know about the following attributes {"refType"=>"0"} for the 'PBXFileReference' isa. (RuntimeError)
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:287:in `each'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:202:in `initialize_from_file'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/recreate_schemes.rb:9:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:231:in `block (2 levels) in run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:343:in `run'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/cli_tools_distributor.rb:91:in `take_off'
	from /Users/mkozjak/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.72.0/bin/fastlane:20:in `<top (required)>'
	from /Users/mkozjak/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/mkozjak/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```
My pbxproj file: https://gist.github.com/7824a4cf3c43ec71abd50c3031fcf14f
References #500 fastlane/fastlane#11438 possibly.

### PR DESCRIPTION
**Pull request by theoriginalgri**
The 'raises if it encounters an unknown attribute in a plist' test was also duplicated before.

Fixes #535.

### CODE REVIEW

File: spec/project/object_spec.rb [hunk 1]
```diff
@@ -157,14 +157,10 @@ module ProjectSpecs
         group.files.should.be.empty
       end
 
-      it 'raises if it encounters an unknown attribute in a plist' do
+      it 'warns if it encounters an unknown attribute in a plist' do
+        STDERR.expects(:puts).times(1)
```
Comment (segiddins) [inline spec/project/object_spec.rb]: can you change this to `UI.expects(:warn).with ...` to test that we actually warn with the expect string?

**Comment by theoriginalgri** [comment]
@segiddins Updated
